version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: stock_analysis_db
    environment:
      POSTGRES_USER: ${DB_USER:-stockuser}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-stockpass}
      POSTGRES_DB: ${DB_NAME:-stockdb}
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-stockuser}"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  postgres_data:

